#nom;ip;estat
vlan_Admin;10.0.1.1/24;DESACTIVAT;
vlan_DMZ;10.0.2.1/24;DESACTIVAT;
vlanAD;10.1.3.1/24;DESACTIVAT;
vlanSOC;10.1.4.1/24;DESACTIVAT;
vlan5;10.1.5.1/24;DESACTIVAT;
vlan6;10.1.6.1/24;DESACTIVAT;
WIFI;10.1.99.1/24;DESACTIVAT;
wg-routers;10.200.0.1/24;DESACTIVAT;
wg-users;10.201.0.1/24;DESACTIVAT;
