module(load="imfile" PollingInterval="10")

# Definir el archivo a monitorizar
input(type="imfile"
      File="/var/log/jsbach/user-actions.log"
      Tag="jsbach-actions:"
      Severity="info"
      Facility="local7")

# Enviar todo lo de local7 al servidor remoto SOC vía UDP (un @)
local7.* @10.1.4.138:514
